name: flag_builder
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  build: ^4.0.0
  path: ^1.9.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
